version: "3.9"
services:
  app:
    container_name: golang_container
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DRIVER=${DB_DRIVER}
      - APP_PORT=${APP_PORT}
    tty: true
    build: .
    ports:
      - 4000:4000
    restart: always
    volumes:
      - .:/app
    depends_on:
      - postgresdb
    networks:
      - nereye

  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - "5432:5432"
    networks:
      - nereye
